config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :artists

  resources :paintings

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/artist.rb
class Artist < ActiveRecord::Base
end

app/models/painting.rb
class Painting < ActiveRecord::Base
  mount_uploader :image, ImageUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < InheritedResources::Base

  private

    def artist_params
      params.require(:artist).permit(:name, :born, :died, :nationality, :field, :image)
    end
end

app/controllers/paintings_controller.rb
class PaintingsController < InheritedResources::Base

  private

    def painting_params
      params.require(:painting).permit(:title, :artist, :body, :year, :material, :genre, :location, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :born %><br>
    <%= f.text_field :born %>
  </div>
  <div class="field">
    <%= f.label :died %><br>
    <%= f.text_field :died %>
  </div>
  <div class="field">
    <%= f.label :nationality %><br>
    <%= f.text_field :nationality %>
  </div>
  <div class="field">
    <%= f.label :field %><br>
    <%= f.text_field :field %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<h1>Listing artists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Born</th>
      <th>Died</th>
      <th>Nationality</th>
      <th>Field</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= artist.born %></td>
        <td><%= artist.died %></td>
        <td><%= artist.nationality %></td>
        <td><%= artist.field %></td>
        <td><%= artist.image %></td>
        <td><%= link_to 'Show', artist %></td>
        <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_artist_path %>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>

<p>
  <strong>Born:</strong>
  <%= @artist.born %>
</p>

<p>
  <strong>Died:</strong>
  <%= @artist.died %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @artist.nationality %>
</p>

<p>
  <strong>Field:</strong>
  <%= @artist.field %>
</p>

<p>
  <strong>Image:</strong>
  <%= @artist.image %>
</p>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FamousPaintingProfiles</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/paintings/_form.html.erb
<%= form_for(@painting) do |f| %>
  <% if @painting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@painting.errors.count, "error") %> prohibited this painting from being saved:</h2>

      <ul>
      <% @painting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :material %><br>
    <%= f.text_field :material %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paintings/_header.html.erb
<div class="container">
   <div id="wrap">
    <div id="header">
      <div class="wrap">
        <div id="logo">

          <a href="index.html"><img src="<%= image_path("banner.jpg") %>" alt="Side Logo" /></a>
        </div>
        <div class="searchform">
          <form class="searchform" action="#" id="cse-search-box">
            <input type="text" name="q" class="s" value="Tìm kiếm" onfocus="if(this.value==this.defaultValue)this.value='';" onblur="if(this.value=='')this.value=this.defaultValue;"/>
            <input type="hidden" name="cx" value="partner-pub-0956577070291964:9991229555" />
            <input type="hidden" name="cof" value="FORID:10" />
            <input type="hidden" name="ie" value="UTF-8" />
          </form>            </div>
      </div>
    </div>
    <div id="nav">
      <ul class="nav superfish">
        <li class="page_item page-item-136 current_page_ancestor current_page_parent"><%= link_to "Bức Họa Nổi Tiếng", paintings_url %></li>
        <li class="page_item page-item-95"><%= link_to "Họa Sĩ Nổi Tiếng", paintings_path %></li>
        <li class="page_item page-item-100"><%= link_to "Lịch Sử Hội Họa Thế Giới", paintings_url %></li>
      </ul>
    </div>
   </div>
</div>

app/views/paintings/edit.html.erb
<h1>Editing painting</h1>

<%= render 'form' %>

<%= link_to 'Show', @painting %> |
<%= link_to 'Back', paintings_path %>

app/views/paintings/index.html.erb
<%= render 'paintings/header' %>
<div id="inner">
  <div id="content-sidebar-wrap">
    <div class="entry">


<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Artist</th>
      <th>Body</th>
      <th>Year</th>
      <th>Material</th>
      <th>Genre</th>
      <th>Location</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paintings.each do |painting| %>
      <tr>
        <td><%= painting.title %></td>
        <td><%= painting.artist %></td>
        <td><%= painting.body %></td>
        <td><%= painting.year %></td>
        <td><%= painting.material %></td>
        <td><%= painting.genre %></td>
        <td><%= painting.location %></td>
        <td><%= image_tag (painting.image), style: "width:200px" %></td>
        <td><%= link_to 'Show', painting %></td>
        <td><%= link_to 'Edit', edit_painting_path(painting) %></td>
        <td><%= link_to 'Destroy', painting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Painting', new_painting_path %>
    </div>
  </div>
</div>

app/views/paintings/new.html.erb
<h1>New painting</h1>

<%= render 'form' %>

<%= link_to 'Back', paintings_path %>

app/views/paintings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @painting.title %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @painting.artist %>
</p>

<p>
  <strong>Body:</strong>
  <%= @painting.body %>
</p>

<p>
  <strong>Year:</strong>
  <%= @painting.year %>
</p>

<p>
  <strong>Material:</strong>
  <%= @painting.material %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @painting.genre %>
</p>

<p>
  <strong>Location:</strong>
  <%= @painting.location %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag (@painting.image), style: "width:200px" %>
</p>

<%= link_to 'Edit', edit_painting_path(@painting) %> |
<%= link_to 'Back', paintings_path %>